//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Not_Bankası.Models.VeriTabani
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NotBankasiEntities : DbContext
    {
        public NotBankasiEntities()
            : base("name=NotBankasiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NotBilgileri> NotBilgileris { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Universite> Universites { get; set; }
        public virtual DbSet<Universite_Bolum> Universite_Bolum { get; set; }
        public virtual DbSet<Universite_Fakulte> Universite_Fakulte { get; set; }
        public virtual DbSet<UyeBilgileri> UyeBilgileris { get; set; }
        public virtual DbSet<YorumBilgileri> YorumBilgileris { get; set; }
        public virtual DbSet<Mesaj> Mesajs { get; set; }
    }
}
