//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Not_Bankası.Models.VeriTabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesaj
    {
        public string İsim { get; set; }
        public string Baslık { get; set; }
        public string Acıklama { get; set; }
        public string Mesaj1 { get; set; }
    }
}
