//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Not_Bankası.Models.VeriTabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotBilgileri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotBilgileri()
        {
            this.UyeBilgileris = new HashSet<UyeBilgileri>();
        }
    
        public int Not_Id { get; set; }
        public string NotAdı { get; set; }
        public string DersAdı { get; set; }
        public string DersOgretimUyesi { get; set; }
        public int Universite_Id { get; set; }
        public string Yıl { get; set; }
        public string Donem { get; set; }
        public string NotunAçıklaması { get; set; }
        public int Uye_Id { get; set; }
        public string NotYolu { get; set; }
    
        public virtual Universite Universite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UyeBilgileri> UyeBilgileris { get; set; }
    }
}
