//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Not_Bankası.Models.VeriTabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Universite_Fakulte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Universite_Fakulte()
        {
            this.Universite_Bolum = new HashSet<Universite_Bolum>();
        }
    
        public int Fakulte_Id { get; set; }
        public string FakulteAdı { get; set; }
        public int Universite_Id { get; set; }
    
        public virtual Universite Universite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Universite_Bolum> Universite_Bolum { get; set; }
    }
}
