//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Not_Bankası.Models.VeriTabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Universite_Bolum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Universite_Bolum()
        {
            this.UyeBilgileris = new HashSet<UyeBilgileri>();
        }
    
        public int Bolum_Id { get; set; }
        public int Fakulte_Id { get; set; }
        public int Universite_Id { get; set; }
        public string BolumAdı { get; set; }
    
        public virtual Universite Universite { get; set; }
        public virtual Universite_Fakulte Universite_Fakulte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UyeBilgileri> UyeBilgileris { get; set; }
    }
}
