//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Not_Bankası.Models.VeriTabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class UyeBilgileri
    {
        public int Uye_Id { get; set; }
        public string KullanıcıAdı { get; set; }
        public string İsim { get; set; }
        public string Soyisim { get; set; }
        public string ResimYolu { get; set; }
        public string EMail { get; set; }
        public string Sifre { get; set; }
        public Nullable<int> Universite_Id { get; set; }
        public Nullable<int> Bolum_Id { get; set; }
        public Nullable<int> Yorum_Id { get; set; }
        public Nullable<int> Not_Id { get; set; }
    
        public virtual NotBilgileri NotBilgileri { get; set; }
        public virtual Universite Universite { get; set; }
        public virtual Universite_Bolum Universite_Bolum { get; set; }
        public virtual YorumBilgileri YorumBilgileri { get; set; }
    }
}
