//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Not_Bankası.Models.VeriTabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class YorumBilgileri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YorumBilgileri()
        {
            this.UyeBilgileris = new HashSet<UyeBilgileri>();
        }
    
        public int Yorum_Id { get; set; }
        public string Yorum { get; set; }
        public int Not_Id { get; set; }
        public int Uye_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UyeBilgileri> UyeBilgileris { get; set; }
    }
}
